# for discovering services and pods
namespace: default
apps:
  docker_ghhelm:
    name: myapp-deployment
    
    replicaCount: 3
    labels:
      app: myapp
      type: docker-ghhelm
    container:
      name: docker-ghhelm-container
      repository: {{ env.repo }}
    resources:
      requests:
        cpu: 0.5
        memory: "1Gi"
      limits:
        cpu: 1.0
        memory: "2Gi"
  pullPolicy: Always

service:
  docker_ghhelm:
    name: myapp-service
    type: LoadBalancer
    protocol: TCP
    externalPort: 80
    internalPort: 80


tolerations: []
