apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.docker_ghhelm.name }}
  labels:
    app: {{ .Values.apps.docker_ghhelm.labels.app }}
    type: {{ .Values.apps.docker_ghhelm.labels.type }}
spec:  
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        app: {{ .Values.apps.docker_ghhelm.labels.app }}
        type: {{ .Values.apps.docker_ghhelm.labels.type }}
    spec:
      containers:
      - name: {{ .Values.apps.docker_ghhelm.container.name }}
        image: {{ .Values.apps.docker_ghhelm.container.repository }}
        ports:
          - containerPort: {{ .Values.service.docker_ghhelm.internalPort }}
        imagePullPolicy: {{ .Values.apps.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.docker_ghhelm.internalPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 8
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.docker_ghhelm.internalPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 8 
        resources:
          requests:
            memory: {{ .Values.apps.docker_ghhelm.resources.requests.memory }}
            cpu: {{ .Values.apps.docker_ghhelm.resources.requests.cpu }}
          limits:
            memory: {{ .Values.apps.docker_ghhelm.resources.limits.memory }}
            cpu: {{ .Values.apps.docker_ghhelm.resources.limits.cpu }}
  replicas: {{ .Values.apps.docker_ghhelm.replicaCount}}
  selector:
    matchLabels:
      type: {{ .Values.apps.docker_ghhelm.labels.type }}
