apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.docker_ghhelm.name }}
spec:
  selector:
    app: {{ .Values.apps.docker_ghhelm.labels.app }}
    type: {{ .Values.apps.docker_ghhelm.labels.type }}
  ports:
    - protocol: {{ .Values.service.docker_ghhelm.protocol }}
      port: {{ .Values.service.docker_ghhelm.externalPort }}
      targetPort: {{ .Values.service.docker_ghhelm.internalPort }}
  type: {{ .Values.service.docker_ghhelm.type }}
