name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gh_helm:${{ github.sha }}


      - name: 'Deploy'
        uses: 'deliverybot/helm@master'
        with:
          token: '${{ github.token }}'
          chart: 'app'
          release: production-myapp
          value-files: './helm-chart/values.yaml'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
